# Introduction


## Motivation

- Revised Fisheries Act: “... the Minister shall take into account the environmental conditions affecting a fish stock."

- `r colorize("Yet <50\\% of DFO’s stock assessments use environmental data", "blue")`

- Only 28% in Pacific Region

\pause

- `r colorize("Leading cause of not using environmental data is availability of the data:", "red")`
  - `r colorize("where")` to find it
  - `r colorize("wrangling")` it (e.g netCDF into R)
  - `r colorize("understanding")` it

\pause

- Open Data is great, but have to convert raw data into `r colorize("usable information", "red")`

## Why an R package?

- R is the computer programming language most widely used by DFO stock assessment
  scientists (the primary audience).

- An R package is the standard way to share code (and data).

- Easy installation:

\textcolor{red}{\texttt{remotes::install\_github("pbs-assess/pacea")}}

\pause

- Ensures proper documentation of data objects and functions (helps users).

- Custom plotting files, help files for everything, fully open source.

- Include vignettes that walk users through various features (already rendered
  on GitHub).

\pause

- All data (except oceanographic model output) is saved within the package
  - no further downloading required
  - not relying on external websites being functional.

<!--
## `pacea` objects (climatic/oceanographic)

Currently, pacea contains (`r colorize("red is updated/new since last year's meeting", "red")`):

- $\cancel{204,039}$ `r colorize(format(nrow(buoy_sst), big.mark = ","), "red")` calculations of daily sea surface
   temperature based on data from `r nrow(buoy_metadata)` buoys

\pause

- outputs from the spatial British Columbia continental margin (BCCM) model,
   `r colorize("now expanded from just Canada's EEZ to include the full model domain,
   extending into US waters", "red")`

\pause

- `r colorize("outputs from the spatial Hindcast of the Salish Sea (HOTSSea)
  physical oceanography model (including Puget Sound), 1980-2018", "red")`

\pause

- NOAA's spatial Optimum Interpolation Sea Surface Temperature (OISST) record
  `r colorize("updated monthly", "red")`

\pause

- $\cancel{9}$ `r colorize(nrow(pacea_indices), "red")` climatic and oceanographic indices, such as the Pacific Decadal Oscillation and those related to El Niño

## `pacea` objects (biological)

- estimates of abundances for Harbour Seals

- estimates of spawning stock biomass and annual recruitments for
 `r colorize("Pacific Hake", "red")` and `r colorize("Pacific Herring", "red")`

- `r colorize("zooplankton biomass anomalies in the Strait of Georgia for 25 species groups", "red")`
-->
